version: "2"

run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: redefines-builtin-id
          disabled: true
        - name: unused-parameter
          disabled: true
